const fs=require("fs");
const path=require("path");
const http=require("http");

const VERSION="26.10.09-BTC-5M-15M-KRAKEN-AMOUNT-FIX";
const BUILD_SHA=process.env.MONITOR_BUILD_SHA||"unknown";
const AGGR_URL=process.env.AGGR_URL||"http://127.0.0.1:9090/trades";
const STATE_FILE=process.env.STATE_FILE||"/data/aggr-trade-state.json";
const LOG_FILE=process.env.LOG_FILE||"/data/aggr-trade.jsonl";
const SYMBOL="BTC";
const MAX_SEEN=20000;
const LOG_MAX_BYTES=2*1024*1024;
const LOG_KEEP_BYTES=1*1024*1024;
const PERIODS=[{name:"5m",ms:5*60*1000},{name:"15m",ms:15*60*1000}];
let state,aggrRequest=null,aggrConnected=false,aggrEvents=0,aggrLastEventAt=null,reconnectTimer=null,alertInFlight=new Set(),logSubscribers=new Set();
function nowIso(){return new Date().toISOString();}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null;}
function ensureDir(file){fs.mkdirSync(path.dirname(file),{recursive:true});}
function log(event,data={}){const row={ts:nowIso(),version:VERSION,event,...data};try{ensureDir(LOG_FILE);fs.appendFileSync(LOG_FILE,JSON.stringify(row)+"\n");for(const res of logSubscribers){try{res.write("data: "+JSON.stringify(row)+"\n\n");}catch{logSubscribers.delete(res);}}const size=fs.statSync(LOG_FILE).size;if(size>LOG_MAX_BYTES){const fd=fs.openSync(LOG_FILE,"r"),buf=Buffer.alloc(LOG_KEEP_BYTES);fs.readSync(fd,buf,0,LOG_KEEP_BYTES,size-LOG_KEEP_BYTES);fs.closeSync(fd);const i=buf.indexOf(10);fs.writeFileSync(LOG_FILE,i>=0?buf.subarray(i+1):buf);}}catch{}}
function defaultSnapshot(){return{periodStart:null,total:0,buy:0,sell:0,buyValue:0,sellValue:0,volume:0,tradePriceValue:0,tradeSize:0,exchanges:{}};}
function defaultState(){return{version:VERSION,strategy:"AGGR_TRADES",periods:{},tradeSeen:[],seen:[],alertsSent:0,lastPeriodTradesPerSec:null,lastAvgPriceByPeriod:{}};}
function loadState(){try{const v=JSON.parse(fs.readFileSync(STATE_FILE,"utf8"));if(v&&typeof v==="object")return v;}catch{}return defaultState();}
function saveState(){try{ensureDir(STATE_FILE);const tmp=STATE_FILE+".tmp";fs.writeFileSync(tmp,JSON.stringify(state));fs.renameSync(tmp,STATE_FILE);}catch{}}
function resetPeriod(period,start){state.periods[period.name]={...defaultSnapshot(),periodStart:start};}
function normalize(raw){const symbol=String(raw?.symbol||raw?.pair||"").toUpperCase().replace(/USDT|USDC|USD|PERP|SWAP|[-_]/g,"");if(symbol!==SYMBOL)return null;const price=num(raw?.price),size=num(raw?.size);if(price===null||size===null||price<=0||size<=0)return null;const count=num(raw?.count);let timestamp=num(raw?.timestamp)??Date.now();if(timestamp<1e12)timestamp*=1000;const exchange=String(raw?.exchange||"AGGR").toUpperCase();if(exchange==="HITBTC")return null;return{id:raw?.id?String(raw.id):"",timestamp,exchange,pair:String(raw?.pair||raw?.symbol||""),side:String(raw?.side||"").toLowerCase(),price,size,count:count&&count>0?count:1,amount:num(raw?.amount)};}
function addTrade(snapshot,e){const count=e.count||1,value=e.exchange==="BITUNIX"?Math.abs(e.size):e.exchange==="KRAKEN"?(String(e.pair||"").toUpperCase().startsWith("PF_")?Math.abs(e.price*e.price*e.size):Math.abs(e.price*e.size)):e.amount!==null&&e.amount>0?Math.abs(e.amount):Math.abs(e.price*e.size)/count;const x=snapshot.exchanges[e.exchange]||(snapshot.exchanges[e.exchange]={trades:0,volume:0,buy:0,sell:0,buyValue:0,sellValue:0});snapshot.total+=count;snapshot.volume+=value;snapshot.tradePriceValue+=e.price*e.size;snapshot.tradeSize+=e.size;x.trades+=count;x.volume+=value;if(e.side==="buy"){snapshot.buy+=count;snapshot.buyValue+=value;x.buy+=count;x.buyValue+=value;}else if(e.side==="sell"){snapshot.sell+=count;snapshot.sellValue+=value;x.sell+=count;x.sellValue+=value;}}
function sendTelegram(text){const token=process.env.TELEGRAM_BOT_TOKEN,chatId=process.env.TELEGRAM_CHAT_ID;if(!token||!chatId)return Promise.resolve(false);return fetch("https://api.telegram.org/bot"+token+"/sendMessage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text}),signal:AbortSignal.timeout(8000)}).then(r=>r.ok).catch(()=>false);}
function marketUrl(period,name){return "https://polymarket.com/event/btc-updown-"+name+"-"+Math.floor(period/1000);}
async function flushPeriod(config,period,snapshot){const key=config.name+":"+period;if(alertInFlight.has(key))return;alertInFlight.add(key);try{const totalValue=snapshot.buyValue+snapshot.sellValue;const buyPct=totalValue>0?(snapshot.buyValue/totalValue)*100:0;const sellPct=totalValue>0?(snapshot.sellValue/totalValue)*100:0;const diff=Math.abs(buyPct-sellPct);const avgPrice=snapshot.tradeSize>0?snapshot.tradePriceValue/snapshot.tradeSize:0;if(totalValue<=0)return;state.lastAvgPriceByPeriod=state.lastAvgPriceByPeriod&&typeof state.lastAvgPriceByPeriod==="object"?state.lastAvgPriceByPeriod:{};const previousAvgPrice=num(state.lastAvgPriceByPeriod[config.name]);const avgChangePct=previousAvgPrice!==null&&previousAvgPrice>0?((avgPrice-previousAvgPrice)/previousAvgPrice)*100:null;state.lastAvgPriceByPeriod[config.name]=avgPrice;saveState();if(avgChangePct===null||Math.abs(avgChangePct)<0.02)return;const avgPriceLine="AVG PRICE: $"+avgPrice.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})+" | "+(avgChangePct===null?"—":(avgChangePct>0?"+":"")+avgChangePct.toFixed(2)+"%");const lines=["🔥 BTC "+config.name,"BUY VALUE: $"+snapshot.buyValue.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}),"SELL VALUE: $"+snapshot.sellValue.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}),"BUY: "+buyPct.toFixed(2)+"% | SELL: "+sellPct.toFixed(2)+"%","DIFF: "+diff.toFixed(2)+"%",avgPriceLine,"",marketUrl(period+config.ms,config.name)];const exchanges=Object.entries(snapshot.exchanges).sort((a,b)=>(b[1].buyValue+b[1].sellValue)-(a[1].buyValue+a[1].sellValue));for(const [name,data] of exchanges)lines.push((name.toUpperCase()==="BINANCE_FUTURES"?"BINANCE":name.toUpperCase())+": $"+(data.buyValue+data.sellValue).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}));const sent=await sendTelegram(lines.join("\n"));log(sent?"TRADE_ALERT_SENT":"TRADE_ALERT_FAILED",{source:"AGGR",periodType:config.name,period,periodEnd:new Date(period).toISOString(),trades:snapshot.total,buy:snapshot.buy,sell:snapshot.sell,buyValue:snapshot.buyValue,sellValue:snapshot.sellValue,buyPct,sellPct,diff,avgPrice,volume:snapshot.volume,tradeExchanges:Object.fromEntries(exchanges)});if(sent){state.alertsSent=Number(state.alertsSent||0)+1;saveState();}}finally{alertInFlight.delete(key);}}
function advancePeriod(config,p){let bucket=state.periods[config.name];while(p>bucket.periodStart){const old=bucket.periodStart;const snapshot={total:bucket.total,buy:bucket.buy,sell:bucket.sell,buyValue:bucket.buyValue||0,sellValue:bucket.sellValue||0,volume:bucket.volume,tradePriceValue:bucket.tradePriceValue||0,tradeSize:bucket.tradeSize||0,exchanges:JSON.parse(JSON.stringify(bucket.exchanges||{}))};resetPeriod(config,old+config.ms);if(snapshot.total>0)flushPeriod(config,old,snapshot);bucket=state.periods[config.name];}return bucket;}
const dedupDiagnostics={KRAKEN:{accepted:0,duplicates:0,lastLogAt:0}};function processRaw(raw){const e=normalize(raw);if(!e)return;const key=e.id?e.exchange+":"+e.pair+":"+e.id:[e.timestamp,e.exchange,e.pair,e.side,e.price,e.size,e.count].join("|");const seen=Array.isArray(state.tradeSeen)?state.tradeSeen:(state.tradeSeen=[]);if(seen.includes(key)){if(e.exchange==="KRAKEN"){const d=dedupDiagnostics.KRAKEN;d.duplicates++;const now=Date.now();if(now-d.lastLogAt>=60000){log("TRADE_DEDUP_DIAGNOSTICS",{exchange:"KRAKEN",accepted:d.accepted,duplicates:d.duplicates,lastTimestamp:e.timestamp,lastPrice:e.price,lastSize:e.size,lastAmount:e.amount});d.accepted=0;d.duplicates=0;d.lastLogAt=now;}}return;}seen.push(key);if(seen.length>MAX_SEEN)seen.splice(0,seen.length-MAX_SEEN);if(e.exchange==="KRAKEN")dedupDiagnostics.KRAKEN.accepted++;for(const config of PERIODS){const p=Math.floor(e.timestamp/config.ms)*config.ms;let bucket=state.periods[config.name];if(p<bucket.periodStart)continue;bucket=advancePeriod(config,p);addTrade(bucket,e);}aggrEvents++;aggrLastEventAt=nowIso();}
function connectAggr(){if(aggrRequest){try{aggrRequest.destroy();}catch{}}const req=http.get(AGGR_URL,res=>{if(res.statusCode!==200){log("AGGR_HTTP_ERROR",{url:AGGR_URL,status:res.statusCode});res.resume();scheduleReconnect();return;}aggrConnected=true;let buffer="";res.setEncoding("utf8");res.on("data",chunk=>{buffer+=chunk.replace(/\r\n/g,"\n").replace(/\r/g,"\n");const frames=buffer.split("\n\n");buffer=frames.pop()||"";for(const frame of frames){const dataLines=frame.split("\n").filter(x=>x.startsWith("data:"));if(!dataLines.length)continue;const payload=dataLines.map(x=>x.slice(5).replace(/^ /,"")).join("\n");try{processRaw(JSON.parse(payload));}catch(e){log("AGGR_EVENT_PARSE_ERROR",{error:String(e.message||e),payload:payload.slice(0,500)});}}});res.on("end",()=>{aggrConnected=false;aggrRequest=null;scheduleReconnect();});res.on("error",e=>{aggrConnected=false;aggrRequest=null;log("AGGR_STREAM_ERROR",{error:String(e.message||e)});scheduleReconnect();});});aggrRequest=req;req.on("error",e=>{aggrConnected=false;aggrRequest=null;log("AGGR_CONNECTION_ERROR",{url:AGGR_URL,error:String(e.message||e)});scheduleReconnect();});}
function scheduleReconnect(){if(reconnectTimer)return;reconnectTimer=setTimeout(()=>{reconnectTimer=null;connectAggr();},3000);}
function diagnostics(){const periods={};for(const config of PERIODS){const p=state.periods[config.name]||defaultSnapshot();periods[config.name]={periodStart:p.periodStart,trades:p.total,buy:p.buy,sell:p.sell,buyValue:p.buyValue||0,sellValue:p.sellValue||0,volume:p.volume,exchanges:p.exchanges};}return{status:"ok",version:VERSION,buildSha:BUILD_SHA,strategy:state.strategy,source:"AGGR",aggrUrl:AGGR_URL,aggrConnected,aggrEvents,aggrLastEventAt,alertsSent:state.alertsSent,periods};}
function startHealth(){const port=Number(process.env.MONITOR_HEALTH_PORT||8080);http.createServer((req,res)=>{const p=String(req.url||"/").split("?")[0];if(p==="/"||p==="/health"||p==="/status"||p==="/stats"){res.writeHead(200,{"content-type":"application/json","cache-control":"no-store"});return res.end(JSON.stringify(diagnostics()));}if(p==="/logs"){let rows=[];try{rows=fs.readFileSync(LOG_FILE,"utf8").split("\n").filter(Boolean).slice(-300).map(x=>JSON.parse(x));}catch{}res.writeHead(200,{"content-type":"application/json"});return res.end(JSON.stringify({status:"ok",events:rows}));}if(p==="/logs/stream"){res.writeHead(200,{"content-type":"text/event-stream","cache-control":"no-cache","connection":"keep-alive"});logSubscribers.add(res);req.on("close",()=>logSubscribers.delete(res));return;}res.writeHead(404);res.end();}).listen(port,"0.0.0.0",()=>log("HEALTH_LISTENING",{port}));}
function main(){ensureDir(STATE_FILE);state=loadState();state.version=VERSION;state.strategy="AGGR_TRADES";state.tradeSeen=Array.isArray(state.tradeSeen)?state.tradeSeen:(Array.isArray(state.seen)?state.seen:[]);state.seen=state.tradeSeen;state.alertsSent=Number(state.alertsSent||0);state.periods=state.periods&&typeof state.periods==="object"?state.periods:{};const now=Date.now();for(const config of PERIODS){const p=Math.floor(now/config.ms)*config.ms;if(!state.periods[config.name]||state.periods[config.name].periodStart==null)resetPeriod(config,p);else if(state.periods[config.name].periodStart!==p)resetPeriod(config,p);else{const bucket=state.periods[config.name];bucket.exchanges=bucket.exchanges&&typeof bucket.exchanges==="object"?bucket.exchanges:{}}}startHealth();connectAggr();setInterval(()=>{const now=Date.now();for(const config of PERIODS){let bucket=state.periods[config.name],current=Math.floor(now/config.ms)*config.ms;while(bucket.periodStart<current){const old=bucket.periodStart;const snapshot={total:bucket.total,buy:bucket.buy,sell:bucket.sell,buyValue:bucket.buyValue||0,sellValue:bucket.sellValue||0,volume:bucket.volume,tradePriceValue:bucket.tradePriceValue||0,tradeSize:bucket.tradeSize||0,exchanges:JSON.parse(JSON.stringify(bucket.exchanges||{}))};resetPeriod(config,old+config.ms);flushPeriod(config,old,snapshot);bucket=state.periods[config.name];}}},1000);log("TRADE_MONITOR_STARTING",{source:"AGGR",tradeUrl:AGGR_URL,symbol:"BTC",periods:PERIODS.map(x=>x.name),filters:[],thresholds:[]});}
main();
