const https = require('https');
const { fetchSymbolFeed, normalizeTs, normalizeSymbol } = require('./liquidation-monitor');
const { TIMEFRAMES, findMarketByEpoch, findNextMarket } = require('./polymarket');
const { sendTelegramMessage } = require('./telegram');

const symbols = ['BTC', 'ETH', 'SOL', 'XRP', 'DOGE', 'BNB', 'HYPE'];
const FRAMEWORKS = ['5m', '15m', '1h', '4h'];
const disabledSymbolsByTimeframe = {
  '5m': ['HYPE'],
  '15m': [],
  '1h': [],
  '4h': []
};
const BOUNDARY_GRACE_MS = 1500;
const REQUEST_TIMEOUT_MS = 15000;
const STATE_PATH = '.monitor-state.json';
const STATE_API_URL = `https://api.github.com/repos/${process.env.GITHUB_REPOSITORY || 'laudinvil/Polymarket-Perps-Monitor'}/contents/${STATE_PATH}?ref=monitor-status`;
const HISTORICAL_URL = 'https://marginpad.io/api/v1/liquidations/recent';
const sentAlerts = new Set();
const timeframeState = new Map();
let stateSha = null;

function emptySymbolState() { return { imbalanceUsd: 0, longUsd: 0, shortUsd: 0, longEvents: 0, shortEvents: 0, events: 0, establishedSign: 0, lastBucket: null, buckets: {} }; }
for (const timeframe of FRAMEWORKS) timeframeState.set(timeframe, new Map());
function sleep(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }
function bucketStart(ts, timeframe) { const size = TIMEFRAMES[timeframe]; return Math.floor(ts / size) * size; }
function nextBoundary(ts) { let next = Infinity; for (const timeframe of FRAMEWORKS) next = Math.min(next, bucketStart(ts, timeframe) + TIMEFRAMES[timeframe]); return next; }
function formatUsd(value) { const sign = value > 0 ? '+' : value < 0 ? '-' : ''; return `${sign}$${Math.round(Math.abs(value)).toLocaleString('en-US')}`; }
function formatAbsUsd(value) { return `$${Math.round(Math.abs(Number(value) || 0)).toLocaleString('en-US')}`; }
function eventSideSign(event) { const side = String(event?.side || event?.direction || '').toLowerCase(); if (side.includes('long')) return 1; if (side.includes('short')) return -1; return 0; }
function eventNotionalUsd(event) { const value = event?.notional ?? event?.usd ?? event?.value ?? event?.amount; const n = Number(value); return Number.isFinite(n) ? Math.abs(n) : 0; }
function githubRequest(method = 'GET', body = undefined) { return new Promise((resolve, reject) => { const url = new URL(STATE_API_URL); const req = https.request({ hostname: url.hostname, path: `${url.pathname}${url.search}`, method, timeout: REQUEST_TIMEOUT_MS, headers: { 'User-Agent': 'Polymarket-Perps-Monitor', 'Accept': 'application/vnd.github+json', 'Authorization': `Bearer ${process.env.GITHUB_TOKEN || ''}`, 'X-GitHub-Api-Version': '2022-11-28' } }, res => { let data = ''; res.setEncoding('utf8'); res.on('data', chunk => { data += chunk; }); res.on('end', () => { let parsed = null; try { parsed = data ? JSON.parse(data) : null; } catch {} if (res.statusCode >= 200 && res.statusCode < 300) return resolve(parsed); const error = new Error(`GitHub state request failed: ${res.statusCode} ${data}`); error.statusCode = res.statusCode; reject(error); }); }); req.on('timeout', () => req.destroy(new Error('GitHub state request timed out'))); req.on('error', reject); if (body !== undefined) req.write(JSON.stringify(body)); req.end(); }); }
function buildStatePayload() { const liquidationTimeframes = {}; for (const timeframe of FRAMEWORKS) { liquidationTimeframes[timeframe] = {}; for (const symbol of symbols) liquidationTimeframes[timeframe][symbol] = timeframeState.get(timeframe).get(symbol) || emptySymbolState(); } return { version: 4, updatedAt: new Date().toISOString(), sentAlerts: [...sentAlerts], liquidationTimeframes }; }
function migrateAlertKey(key) { if (typeof key !== 'string') return null; const current = key.match(/^(5m|15m|1h|4h|1d):([A-Z]+):(\d+):(-?1)$/); if (current) return key; const legacy = key.match(/^(5m|15m|1h|4h|1d):([A-Z]+):(\d+):(-?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?)$/i); if (!legacy) return null; const value = Number(legacy[4]); if (!Number.isFinite(value) || value === 0) return null; return `${legacy[1]}:${legacy[2]}:${legacy[3]}:${value > 0 ? 1 : -1}`; }
function mergeStateAlerts(state) { for (const key of [...(state?.sentAlerts || []), ...(state?.alerts || [])]) { const migrated = migrateAlertKey(key); if (migrated) sentAlerts.add(migrated); } }
function normalizeSavedState(saved) { const state = { ...emptySymbolState(), ...saved, buckets: saved?.buckets && typeof saved.buckets === 'object' ? saved.buckets : {} }; let longUsd = 0, shortUsd = 0, longEvents = 0, shortEvents = 0; for (const bucket of Object.values(state.buckets)) { longUsd += Math.max(0, Number(bucket?.longUsd) || 0); shortUsd += Math.max(0, Number(bucket?.shortUsd) || 0); longEvents += Math.max(0, Number(bucket?.longEvents) || 0); shortEvents += Math.max(0, Number(bucket?.shortEvents) || 0); } if (Object.keys(state.buckets).length) { state.longUsd = longUsd; state.shortUsd = shortUsd; state.longEvents = longEvents; state.shortEvents = shortEvents; state.events = longEvents + shortEvents; } else { state.longUsd = Number(state.longUsd) || 0; state.shortUsd = Number(state.shortUsd) || 0; state.longEvents = Number(state.longEvents) || 0; state.shortEvents = Number(state.shortEvents) || 0; state.events = Number(state.events) || state.longEvents + state.shortEvents; } state.imbalanceUsd = state.shortUsd - state.longUsd; state.establishedSign = state.imbalanceUsd > 0 ? 1 : state.imbalanceUsd < 0 ? -1 : 0; return state; }
async function loadState() { if (!process.env.GITHUB_TOKEN) return; try { const result = await githubRequest('GET'); stateSha = result?.sha || null; if (!result?.content) return; const state = JSON.parse(Buffer.from(result.content.replace(/\s/g, ''), 'base64').toString('utf8')); mergeStateAlerts(state); for (const timeframe of FRAMEWORKS) { const map = timeframeState.get(timeframe); for (const symbol of symbols) { const saved = state.liquidationTimeframes?.[timeframe]?.[symbol]; if (saved) map.set(symbol, normalizeSavedState(saved)); } } console.log(`STATE LOADED ${state.updatedAt || 'unknown'}; dedup keys=${sentAlerts.size}; imbalance rebuilt from Short-Long; 1d disabled`); } catch (error) { if (error.statusCode === 404) console.log('STATE LOAD: no persisted state found; starting clean'); else console.warn(`STATE LOAD FAILED: ${error.message}`); } }
async function saveState() { if (!process.env.GITHUB_TOKEN) return false; for (let attempt = 1; attempt <= 5; attempt++) { try { let latest = null; try { latest = await githubRequest('GET'); } catch (error) { if (error.statusCode !== 404) throw error; } stateSha = latest?.sha || null; if (latest?.content) { try { mergeStateAlerts(JSON.parse(Buffer.from(latest.content.replace(/\s/g, ''), 'base64').toString('utf8'))); } catch {} } const payload = buildStatePayload(); const body = { message: 'Persist liquidation monitor state', content: Buffer.from(JSON.stringify(payload, null, 2)).toString('base64'), branch: 'monitor-status', ...(stateSha ? { sha: stateSha } : {}) }; const result = await githubRequest('PUT', body); stateSha = result?.content?.sha || stateSha; console.log(`STATE SAVED ${payload.updatedAt}`); return true; } catch (error) { if (error.statusCode !== 409 || attempt === 5) { console.warn(`STATE SAVE FAILED: ${error.message}`); return false; } await sleep(250 * attempt); } } return false; }
async function reserveAlertKey(alertKey) { if (sentAlerts.has(alertKey)) { console.log(`ALERT DUPLICATE SUPPRESSED ${alertKey}`); return false; } if (!process.env.GITHUB_TOKEN) return true; for (let attempt = 1; attempt <= 5; attempt++) { try { let latest = null; try { latest = await githubRequest('GET'); } catch (error) { if (error.statusCode !== 404) throw error; } if (latest?.content) { try { const latestState = JSON.parse(Buffer.from(latest.content.replace(/\s/g, ''), 'base64').toString('utf8')); const latestKeys = new Set(); for (const key of [...(latestState.sentAlerts || []), ...(latestState.alerts || [])]) { const migrated = migrateAlertKey(key); if (migrated) latestKeys.add(migrated); } if (latestKeys.has(alertKey)) { sentAlerts.add(alertKey); console.log(`ALERT DUPLICATE SUPPRESSED ${alertKey}`); return false; } } catch {} } console.log(`ALERT ELIGIBLE ${alertKey}`); return true; } catch (error) { if (error.statusCode !== 409 || attempt === 5) { console.warn(`ALERT DEDUP CHECK FAILED ${alertKey}: ${error.message}`); return false; } await sleep(250 * attempt); } } return false; }
async function markAlertSent(alertKey) { sentAlerts.add(alertKey); await saveState(); console.log(`ALERT MARKED SENT ${alertKey}`); }
function extractHistoricalBuckets(json) { const roots = [json?.data, json]; const candidates = ['buckets', 'histogram', 'rows', 'series', 'bars', 'points', 'items', 'data']; const seen = new Set(); const queue = roots.map(root => ({ value: root, depth: 0 })); while (queue.length) { const { value, depth } = queue.shift(); if (!value || depth > 3 || typeof value !== 'object' || seen.has(value)) continue; seen.add(value); if (Array.isArray(value)) { if (value.some(row => row && typeof row === 'object' && !Array.isArray(row))) return value; continue; } for (const key of candidates) if (Array.isArray(value[key]) && value[key].length) return value[key]; for (const child of Object.values(value)) if (child && typeof child === 'object') queue.push({ value: child, depth: depth + 1 }); } return []; }
function numericValue(value) { if (value === null || value === undefined || value === '') return 0; if (typeof value === 'number') return Number.isFinite(value) ? value : 0; if (typeof value === 'object') { for (const key of ['usd', 'value', 'notional', 'amount', 'total', 'volume', 'vol']) { const n = numericValue(value[key]); if (n) return n; } return 0; } const n = Number(String(value).replace(/[$,\s]/g, '')); return Number.isFinite(n) ? n : 0; }
function bucketValue(row, names, direction) { for (const name of names) { const value = numericValue(row?.[name]); if (value !== 0) return Math.abs(value); } if (row && typeof row === 'object') for (const [key, raw] of Object.entries(row)) { const lower = key.toLowerCase(); if (!lower.includes(direction)) continue; if (!/(usd|notional|volume|value|amount|liquid)/i.test(lower) && lower !== direction) continue; const value = numericValue(raw); if (value !== 0) return Math.abs(value); } return 0; }
function normalizeHistoricalTimestamp(value) { if (value === null || value === undefined || value === '') return null; if (value instanceof Date) { const ts = value.getTime(); return Number.isFinite(ts) && ts > 0 ? ts : null; } if (Array.isArray(value)) return normalizeHistoricalTimestamp(value[0]); if (typeof value === 'object') { for (const key of ['$date', 'date', 'timestamp', 'ts', 'time', 'start', 'startTime', 'epoch']) if (Object.prototype.hasOwnProperty.call(value, key)) { const ts = normalizeHistoricalTimestamp(value[key]); if (ts) return ts; } return null; } if (typeof value === 'string') { const trimmed = value.trim(); if (!trimmed) return null; const numeric = Number(trimmed); if (Number.isFinite(numeric) && numeric > 0) return normalizeHistoricalTimestamp(numeric); const parsed = Date.parse(trimmed); return Number.isFinite(parsed) && parsed > 0 ? parsed : null; } const n = Number(value); if (!Number.isFinite(n) || n <= 0) return null; if (n < 1e11) return n * 1000; if (n < 1e14) return n; if (n < 1e17) return n / 1000; return n / 1000000; }
function historicalRowTs(row) { if (Array.isArray(row)) return normalizeHistoricalTimestamp(row[0]); const aliases = ['ts', 'timestamp', 'time', 't', 'bucket', 'start', 'startTime', 'start_ts', 'startTimeMs', 'bucketStart', 'bucket_start', 'epoch', 'date']; for (const key of aliases) { const ts = normalizeHistoricalTimestamp(row?.[key]); if (ts) return ts; } if (row && typeof row === 'object') for (const [key, raw] of Object.entries(row)) { if (!/(time|timestamp|bucket|start|epoch|date|^ts$)/i.test(key)) continue; const ts = normalizeHistoricalTimestamp(raw); if (ts) return ts; } return null; }
async function fetchHistoricalEvents(symbol, timeframe) { const minutes = ({ '15m': 15, '1h': 60, '4h': 240 })[timeframe]; if (!minutes) return { events: [], buckets: new Set() }; const url = `${HISTORICAL_URL}?symbol=${encodeURIComponent(symbol)}&minutes=${Math.max(minutes * 2, 60)}`; try { const response = await fetch(url, { headers: { accept: 'application/json' } }); if (!response.ok) throw new Error(`MarginPad historical request failed: ${response.status}`); const json = await response.json(); const rows = extractHistoricalBuckets(json); const events = []; const buckets = new Set(); let timestampedRows = 0; let valuedRows = 0; for (const row of rows) { const ts = historicalRowTs(row); if (!ts) continue; timestampedRows++; const period = bucketStart(ts, timeframe); buckets.add(period); const longUsd = bucketValue(row, ['long_liquidations', 'longLiquidations', 'long_usd', 'longUsd', 'long_volume', 'longVolume', 'longNotional', 'long_notional', 'long', 'buy'], 'long'); const shortUsd = bucketValue(row, ['short_liquidations', 'shortLiquidations', 'short_usd', 'shortUsd', 'short_volume', 'shortVolume', 'shortNotional', 'short_notional', 'short', 'sell'], 'short'); if (longUsd > 0 || shortUsd > 0) { valuedRows++; events.push({ symbol, ts, period, longUsd, shortUsd, raw: row }); } } console.log(`HISTORICAL ${timeframe} ${symbol}: rows=${rows.length} timestamped=${timestampedRows} buckets=${buckets.size} valued=${valuedRows} events=${events.length}`); return { events, buckets }; } catch (error) { console.warn(`HISTORICAL ${timeframe} ${symbol} FAILED: ${error.message}`); return { events: [], buckets: new Set() }; } }
function applyCompletedBucket(timeframe, symbol, period, longUsd, shortUsd, longEvents = 0, shortEvents = 0) { const map = timeframeState.get(timeframe); if (!map) return null; let state = map.get(symbol) || emptySymbolState(); state = normalizeSavedState(state); if (state.lastBucket !== null && period <= state.lastBucket) return null; longUsd = Math.max(0, Number(longUsd) || 0); shortUsd = Math.max(0, Number(shortUsd) || 0); state.longUsd += longUsd; state.shortUsd += shortUsd; state.longEvents += Math.max(0, Number(longEvents) || 0); state.shortEvents += Math.max(0, Number(shortEvents) || 0); state.events = state.longEvents + state.shortEvents; state.imbalanceUsd = state.shortUsd - state.longUsd; state.establishedSign = state.imbalanceUsd > 0 ? 1 : state.imbalanceUsd < 0 ? -1 : 0; state.lastBucket = period; state.buckets[String(period)] = { longUsd, shortUsd, longEvents: Math.max(0, Number(longEvents) || 0), shortEvents: Math.max(0, Number(shortEvents) || 0) }; map.set(symbol, state); return state; }
function crossingFor(timeframe, symbol, before, after, period) { if (before === after) return null; if (before === 0 && after === 0) return null; if (before !== 0 && after !== 0 && Math.sign(before) === Math.sign(after)) return null; return { timeframe, symbol, before, after, period }; }
async function sendCrossingAlert(crossing, state, longUsd, shortUsd, longEvents, shortEvents) { const alertKey = `${crossing.timeframe}:${crossing.symbol}:${crossing.period}:${crossing.after > 0 ? 1 : -1}`; if (!(await reserveAlertKey(alertKey))) return; let market = null; try { market = await findNextMarket(crossing.symbol, Date.now(), crossing.timeframe); } catch (error) { console.warn(`POLYMARKET LOOKUP FAILED ${crossing.timeframe} ${crossing.symbol}: ${error.message}`); } const marketUrl = market?.url || null; const isUp = crossing.after > 0; const signal = isUp ? 'BUY UP' : 'BUY DOWN'; const color = isUp ? '🟢' : '🔴'; const marketSection = marketUrl ? `\n➡️ NEXT Polymarket ${crossing.timeframe}\n${marketUrl}` : ''; const message = `${color} ${crossing.symbol} · ${crossing.timeframe} · ${signal}\n\nPrevious imbalance: ${formatUsd(crossing.before)}\nNew imbalance: ${formatUsd(crossing.after)}\n${formatUsd(longUsd)} LONG · ${formatUsd(-shortUsd)} SHORT\nLong total: ${formatAbsUsd(state.longUsd)}\nShort total: ${formatAbsUsd(state.shortUsd)}\n${longEvents} LONG events\n${shortEvents} SHORT events${marketSection}`; try { await sendTelegramMessage(message); await markAlertSent(alertKey); console.log(`ALERT SENT ${crossing.timeframe} ${crossing.symbol} ${signal}`); } catch (error) { console.warn(`ALERT SEND FAILED ${crossing.timeframe} ${crossing.symbol}: ${error.message}`); } }
async function processHistorical(timeframe) { for (const symbol of symbols) { const map = timeframeState.get(timeframe); if (!map) continue; const result = await fetchHistoricalEvents(symbol, timeframe); const state = map.get(symbol) || emptySymbolState(); for (const event of result.events.sort((a, b) => a.period - b.period)) { if (state.lastBucket !== null && event.period <= state.lastBucket) continue; applyCompletedBucket(timeframe, symbol, event.period, event.longUsd, event.shortUsd, 0, 0); } } }
async function processLive(timeframe, boundary) { const period = bucketStart(boundary - 1, timeframe); const disabledSymbols = new Set(disabledSymbolsByTimeframe[timeframe] || []); const activeSymbols = symbols.filter(symbol => !disabledSymbols.has(symbol)); await Promise.all(activeSymbols.map(async symbol => { const events = await fetchSymbolFeed(symbol); const state = timeframeState.get(timeframe).get(symbol) || emptySymbolState(); let longUsd = 0, shortUsd = 0, longEvents = 0, shortEvents = 0; for (const event of events || []) { const ts = normalizeTs(event); if (!Number.isFinite(ts) || bucketStart(ts, timeframe) !== period) continue; const side = eventSideSign(event), value = eventNotionalUsd(event); if (side > 0) { longUsd += value; longEvents++; } else if (side < 0) { shortUsd += value; shortEvents++; } } const before = state.imbalanceUsd; const next = applyCompletedBucket(timeframe, symbol, period, longUsd, shortUsd, longEvents, shortEvents); if (!next) return; console.log(JSON.stringify({ timeframe, symbol, period, longUsd, shortUsd, imbalanceUsd: next.imbalanceUsd, establishedSign: next.establishedSign, lastBucket: next.lastBucket })); const crossing = crossingFor(timeframe, symbol, before, next.imbalanceUsd, period); if (crossing) await sendCrossingAlert(crossing, next, longUsd, shortUsd, longEvents, shortEvents); })); }
async function main() { await loadState(); console.log('Multi-timeframe liquidation monitor started; 1d DISABLED; symbols=BTC,ETH,SOL,XRP,DOGE,BNB,HYPE; timeframes=5m,15m,1h,4h; historical API for 15m/1h/4h'); await processHistorical('15m'); await processHistorical('1h'); await processHistorical('4h'); await saveState(); while (true) { const now = Date.now(); const boundary = nextBoundary(now); const wait = Math.max(1000, boundary - now + BOUNDARY_GRACE_MS); console.log(`Waiting for next timeframe boundary in ${Math.round(wait / 1000)}s`); await sleep(wait); const current = Date.now(); for (const timeframe of FRAMEWORKS) { const size = TIMEFRAMES[timeframe]; const due = bucketStart(current, timeframe); if (Math.abs(current - due) <= BOUNDARY_GRACE_MS * 2) { console.log(`TIMEFRAME BOUNDARY REACHED; due=${timeframe}`); await processLive(timeframe, due); } } await saveState(); } }
main().catch(error => { console.error(error); process.exitCode = 1; });
