const https = require('https');
const { fetchSymbolFeed, normalizeTs } = require('./liquidation-monitor');
const { TIMEFRAMES, findNextMarket } = require('./polymarket');
const { sendTelegramMessage } = require('./telegram');

const symbols = ['BTC', 'ETH', 'SOL', 'XRP', 'DOGE', 'BNB', 'HYPE'];
const FRAMEWORKS = ['5m', '15m', '1h', '4h'];
const ALERT_FRAMEWORKS = ['5m', '15m', '1h', '4h'];
const INVERTED_DIRECTION_TIMEFRAMES = new Set(['15m']);
const BOUNDARY_GRACE_MS = 1500;
const REQUEST_TIMEOUT_MS = 15000;
const STATE_PATH = '.monitor-state.json';
const STATE_API_URL = `https://api.github.com/repos/${process.env.GITHUB_REPOSITORY || 'laudinvil/Polymarket-Perps-Monitor'}/contents/${STATE_PATH}?ref=monitor-status`;
const HISTORICAL_URL = 'https://marginpad.io/api/v1/liquidations/recent';

const sentAlerts = new Set();
const timeframeState = new Map();
const contrarianState = new Map();
let stateSha = null;

function empty() { return { imbalanceUsd: 0, longUsd: 0, shortUsd: 0, longEvents: 0, shortEvents: 0, events: 0, establishedSign: 0, lastBucket: null, buckets: {} }; }
for (const timeframe of FRAMEWORKS) { timeframeState.set(timeframe, new Map()); contrarianState.set(timeframe, { symbol: null, sign: 0 }); }
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
function bucketStart(ts, timeframe) { return Math.floor(ts / TIMEFRAMES[timeframe]) * TIMEFRAMES[timeframe]; }
function nextBoundary(ts) { return Math.min(...FRAMEWORKS.map(t => bucketStart(ts, t) + TIMEFRAMES[t])); }
function formatUsd(v) { const s = v > 0 ? '+' : v < 0 ? '-' : ''; return `${s}$${Math.round(Math.abs(v)).toLocaleString('en-US')}`; }
function side(event) { const s = String(event?.side || event?.direction || '').toLowerCase(); return s.includes('long') ? 1 : s.includes('short') ? -1 : 0; }
function notional(event) { const n = Number(event?.notional ?? event?.usd ?? event?.value ?? event?.amount); return Number.isFinite(n) ? Math.abs(n) : 0; }

function githubRequest(method = 'GET', body) {
  return new Promise((resolve, reject) => {
    const u = new URL(STATE_API_URL);
    const req = https.request({ hostname: u.hostname, path: u.pathname + u.search, method, timeout: REQUEST_TIMEOUT_MS, headers: { 'User-Agent': 'Polymarket-Perps-Monitor', Accept: 'application/vnd.github+json', Authorization: `Bearer ${process.env.GITHUB_TOKEN || ''}`, 'X-GitHub-Api-Version': '2022-11-28' } }, res => {
      let data = ''; res.setEncoding('utf8'); res.on('data', chunk => data += chunk); res.on('end', () => { let parsed = null; try { parsed = data ? JSON.parse(data) : null; } catch {} if (res.statusCode >= 200 && res.statusCode < 300) return resolve(parsed); const error = new Error(`GitHub state request failed: ${res.statusCode} ${data}`); error.statusCode = res.statusCode; reject(error); });
    });
    req.on('timeout', () => req.destroy(new Error('GitHub state request timed out'))); req.on('error', reject); if (body !== undefined) req.write(JSON.stringify(body)); req.end();
  });
}
function migrateAlertKey(key) { if (typeof key !== 'string') return null; const match = key.match(/^(5m|15m|1h|4h):([A-Z]+):(\d+)(?::(-?1))?$/); if (!match) return null; return match[4] ? `${match[1]}:${match[2]}:${match[3]}:${match[4]}` : `${match[1]}:${match[2]}:${match[3]}`; }
function mergeAlerts(state) { for (const key of [...(state?.sentAlerts || []), ...(state?.alerts || [])]) { const normalized = migrateAlertKey(key); if (normalized) sentAlerts.add(normalized); } }
function normalizeSavedState(saved) { const state = { ...empty(), ...saved, buckets: saved?.buckets && typeof saved.buckets === 'object' ? saved.buckets : {} }; const periods = Object.keys(state.buckets).map(Number).filter(Number.isFinite).sort((a,b)=>a-b); const lastPeriod = state.lastBucket !== null && Number.isFinite(Number(state.lastBucket)) ? Number(state.lastBucket) : periods.at(-1); const bucket = lastPeriod !== undefined ? state.buckets[String(lastPeriod)] : null; if (bucket) { state.lastBucket=lastPeriod; state.longUsd=Math.max(0,Number(bucket.longUsd)||0); state.shortUsd=Math.max(0,Number(bucket.shortUsd)||0); state.longEvents=Math.max(0,Number(bucket.longEvents)||0); state.shortEvents=Math.max(0,Number(bucket.shortEvents)||0); } state.events=state.longEvents+state.shortEvents; state.imbalanceUsd=state.shortUsd-state.longUsd; state.establishedSign=state.imbalanceUsd>0?1:state.imbalanceUsd<0?-1:0; return state; }
function buildStatePayload() { const liquidationTimeframes={}; for(const timeframe of FRAMEWORKS){ liquidationTimeframes[timeframe]={}; for(const symbol of symbols) liquidationTimeframes[timeframe][symbol]=timeframeState.get(timeframe).get(symbol)||empty(); } return {version:9,updatedAt:new Date().toISOString(),sentAlerts:[...sentAlerts],liquidationTimeframes,contrarianTimeframes:Object.fromEntries(FRAMEWORKS.map(t=>[t,contrarianState.get(t)||{symbol:null,sign:0}]))}; }
async function loadState(){ if(!process.env.GITHUB_TOKEN)return; try{const response=await githubRequest(); stateSha=response?.sha||null;if(!response?.content)return;const state=JSON.parse(Buffer.from(response.content.replace(/\s/g,''),'base64').toString('utf8'));mergeAlerts(state);for(const timeframe of FRAMEWORKS){for(const symbol of symbols){const saved=state.liquidationTimeframes?.[timeframe]?.[symbol];if(saved)timeframeState.get(timeframe).set(symbol,normalizeSavedState(saved));}const savedContrarian=state.contrarianTimeframes?.[timeframe];if(savedContrarian)contrarianState.set(timeframe,{symbol:savedContrarian.symbol||null,sign:Number(savedContrarian.sign)||0});}console.log(`STATE LOADED ${state.updatedAt||'unknown'}; 5m contrarian; 15m inverted direction; 1h/4h normal direction`);}catch(error){if(error.statusCode===404)console.log('STATE LOAD: no persisted state found; starting clean');else console.warn(`STATE LOAD FAILED: ${error.message}`);}}
async function saveState(){if(!process.env.GITHUB_TOKEN)return false;for(let attempt=1;attempt<=5;attempt++){try{let response=null;try{response=await githubRequest();}catch(error){if(error.statusCode!==404)throw error;}stateSha=response?.sha||null;if(response?.content){try{mergeAlerts(JSON.parse(Buffer.from(response.content.replace(/\s/g,''),'base64').toString('utf8')));}catch{}}const payload=buildStatePayload();const body={message:'Persist liquidation monitor state',content:Buffer.from(JSON.stringify(payload,null,2)).toString('base64'),branch:'monitor-status',...(stateSha?{sha:stateSha}:{})};const output=await githubRequest('PUT',body);stateSha=output?.content?.sha||stateSha;console.log(`STATE SAVED ${payload.updatedAt}`);return true;}catch(error){if(error.statusCode!==409||attempt===5){console.warn(`STATE SAVE FAILED: ${error.message}`);return false;}await sleep(250*attempt);}}return false;}
async function reserveAlertKey(key){if(sentAlerts.has(key)){console.log(`ALERT DUPLICATE SUPPRESSED ${key}`);return false;}if(!process.env.GITHUB_TOKEN)return true;try{const response=await githubRequest();if(response?.content){const state=JSON.parse(Buffer.from(response.content.replace(/\s/g,''),'base64').toString('utf8'));const keys=new Set([...(state.sentAlerts||[]),...(state.alerts||[])].map(migrateAlertKey).filter(Boolean));if(keys.has(key)){sentAlerts.add(key);console.log(`ALERT DUPLICATE SUPPRESSED ${key}`);return false;}}return true;}catch(error){console.warn(`ALERT DEDUP CHECK FAILED ${key}: ${error.message}`);return false;}}
async function markAlertSent(key){sentAlerts.add(key);await saveState();console.log(`ALERT MARKED SENT ${key}`);}
function extractHistoricalBuckets(json){const roots=[json?.data,json],candidates=['buckets','histogram','rows','series','bars','points','items','data'],seen=new Set(),queue=roots.map(value=>({value,depth:0}));while(queue.length){const{value,depth}=queue.shift();if(!value||depth>3||typeof value!=='object'||seen.has(value))continue;seen.add(value);if(Array.isArray(value)){if(value.some(row=>row&&typeof row==='object'&&!Array.isArray(row)))return value;continue;}for(const key of candidates)if(Array.isArray(value[key])&&value[key].length)return value[key];for(const child of Object.values(value))if(child&&typeof child==='object')queue.push({value:child,depth:depth+1});}return[];}
function numericValue(value){if(value===null||value===undefined||value==='')return 0;if(typeof value==='number')return Number.isFinite(value)?value:0;if(typeof value==='object')for(const key of ['usd','value','notional','amount','total','volume','vol']){const n=numericValue(value[key]);if(n)return n;}const n=Number(String(value).replace(/[$,\s]/g,''));return Number.isFinite(n)?n:0;}
function bucketValue(row,names,direction){for(const name of names){const value=numericValue(row?.[name]);if(value!==0)return Math.abs(value);}if(row&&typeof row==='object')for(const[key,raw]of Object.entries(row)){const lower=key.toLowerCase();if(!lower.includes(direction))continue;if(!/(usd|notional|volume|value|amount|liquid)/i.test(lower)&&lower!==direction)continue;const value=numericValue(raw);if(value!==0)return Math.abs(value);}return 0;}
function normalizeHistoricalTimestamp(value){if(value===null||value===undefined||value==='')return null;if(Array.isArray(value))return normalizeHistoricalTimestamp(value[0]);if(typeof value==='object')for(const key of ['$date','date','timestamp','ts','time','start','startTime','epoch'])if(Object.prototype.hasOwnProperty.call(value,key)){const t=normalizeHistoricalTimestamp(value[key]);if(t)return t;}if(typeof value==='string'){const n=Number(value.trim());if(Number.isFinite(n)&&n>0)return normalizeHistoricalTimestamp(n);const parsed=Date.parse(value.trim());return Number.isFinite(parsed)&&parsed>0?parsed:null;}const n=Number(value);if(!Number.isFinite(n)||n<=0)return null;if(n<1e11)return n*1000;if(n<1e14)return n;if(n<1e17)return n/1000;return n/1e6;}
function historicalRowTs(row){if(Array.isArray(row))return normalizeHistoricalTimestamp(row[0]);for(const key of ['ts','timestamp','time','t','bucket','start','startTime','start_ts','startTimeMs','bucketStart','bucket_start','epoch','date']){const t=normalizeHistoricalTimestamp(row?.[key]);if(t)return t;}if(row&&typeof row==='object')for(const[key,value]of Object.entries(row))if(/(time|timestamp|bucket|start|epoch|date|^ts$)/i.test(key)){const t=normalizeHistoricalTimestamp(value);if(t)return t;}return null;}
async function fetchHistoricalEvents(symbol,timeframe){const minutes=({'15m':15,'1h':60,'4h':240})[timeframe];if(!minutes)return{events:[]};const url=`${HISTORICAL_URL}?symbol=${encodeURIComponent(symbol)}&minutes=${Math.max(minutes*2,60)}`;try{const response=await fetch(url,{headers:{accept:'application/json'}});if(!response.ok)throw new Error(`MarginPad historical request failed: ${response.status}`);const rows=extractHistoricalBuckets(await response.json()),events=[];for(const row of rows){const ts=historicalRowTs(row);if(!ts)continue;const period=bucketStart(ts,timeframe),longUsd=bucketValue(row,['long_liquidations','longLiquidations','long_usd','longUsd','long_volume','longVolume','longNotional','long_notional','long','buy'],'long'),shortUsd=bucketValue(row,['short_liquidations','shortLiquidations','short_usd','shortUsd','short_volume','shortVolume','shortNotional','short_notional','short','sell'],'short');if(longUsd>0||shortUsd>0)events.push({period,longUsd,shortUsd});}return{events};}catch(error){console.warn(`HISTORICAL ${timeframe} ${symbol} FAILED: ${error.message}`);return{events:[]};}}
function applyCompletedBucket(timeframe,symbol,period,longUsd,shortUsd,longEvents=0,shortEvents=0){const map=timeframeState.get(timeframe);if(!map)return null;const previous=map.get(symbol)||empty();if(previous.lastBucket!==null&&period<=previous.lastBucket)return null;const state={...previous};state.longUsd=Math.max(0,Number(longUsd)||0);state.shortUsd=Math.max(0,Number(shortUsd)||0);state.longEvents=Math.max(0,Number(longEvents)||0);state.shortEvents=Math.max(0,Number(shortEvents)||0);state.events=state.longEvents+state.shortEvents;state.imbalanceUsd=state.shortUsd-state.longUsd;state.establishedSign=state.imbalanceUsd>0?1:state.imbalanceUsd<0?-1:0;state.lastBucket=period;state.buckets={...state.buckets,[String(period)]:{longUsd:state.longUsd,shortUsd:state.shortUsd,longEvents:state.longEvents,shortEvents:state.shortEvents}};map.set(symbol,state);return state;}

async function sendLargestAlert(timeframe,period,candidate){if(!candidate||candidate.state.imbalanceUsd===0)return;const sign=candidate.state.imbalanceUsd>0?1:-1;const alertKey=`${timeframe}:${candidate.symbol}:${period}`;if(!(await reserveAlertKey(alertKey)))return;let market=null;try{market=await findNextMarket(candidate.symbol,Date.now(),timeframe);}catch(error){console.warn(`POLYMARKET LOOKUP FAILED ${timeframe} ${candidate.symbol}: ${error.message}`);}const effectiveSign=INVERTED_DIRECTION_TIMEFRAMES.has(timeframe)?-sign:sign;const direction=effectiveSign>0?'BUY UP':'BUY DOWN';const color=effectiveSign>0?'🟢':'🔴';const link=market?.url?`\
➡️ NEXT Polymarket ${timeframe}\
${market.url}`:'';const msg=`${color} ${candidate.symbol} · ${timeframe} · ${direction}\
\
Imbalance: ${formatUsd(candidate.state.imbalanceUsd)}\
${formatUsd(candidate.state.longUsd)} LONG · ${formatUsd(candidate.state.shortUsd)} SHORT${link}`;try{await sendTelegramMessage(msg);await markAlertSent(alertKey);console.log(`LARGEST IMBALANCE ALERT SENT ${timeframe} ${candidate.symbol} ${direction} ${formatUsd(candidate.state.imbalanceUsd)}`);}catch(error){console.warn(`LARGEST IMBALANCE ALERT SEND FAILED ${timeframe} ${candidate.symbol}: ${error.message}`);}}
async function sendContrarianAlert(timeframe,period,candidate,majoritySign){if(!candidate||!majoritySign||candidate.state.imbalanceUsd===0)return;const sign=candidate.state.imbalanceUsd>0?1:-1;const previous=contrarianState.get(timeframe)||{symbol:null,sign:0};if(previous.symbol===candidate.symbol&&previous.sign===sign){console.log(`CONTRARIAN CONTINUATION SUPPRESSED ${timeframe} ${candidate.symbol}`);return;}const alertKey=`${timeframe}:${candidate.symbol}:${period}:${sign}`;if(!(await reserveAlertKey(alertKey)))return;let market=null;try{market=await findNextMarket(candidate.symbol,Date.now(),timeframe);}catch(error){console.warn(`POLYMARKET LOOKUP FAILED ${timeframe} ${candidate.symbol}: ${error.message}`);}const effectiveSign=INVERTED_DIRECTION_TIMEFRAMES.has(timeframe)?-sign:sign;const direction=effectiveSign>0?'BUY UP':'BUY DOWN';const color=effectiveSign>0?'🟢':'🔴';const link=market?.url?`\
➡️ NEXT Polymarket ${timeframe}\
${market.url}`:'';const msg=`${color} ${candidate.symbol} · ${timeframe} · ${direction}\
\
Imbalance: ${formatUsd(candidate.state.imbalanceUsd)}\
${formatUsd(candidate.state.longUsd)} LONG · ${formatUsd(candidate.state.shortUsd)} SHORT${link}`;try{await sendTelegramMessage(msg);contrarianState.set(timeframe,{symbol:candidate.symbol,sign});await markAlertSent(alertKey);console.log(`6-VS-1 CONTRARIAN ALERT SENT ${timeframe} ${candidate.symbol} ${direction} ${formatUsd(candidate.state.imbalanceUsd)}`);}catch(error){console.warn(`6-VS-1 CONTRARIAN ALERT SEND FAILED ${timeframe} ${candidate.symbol}: ${error.message}`);}}
function detectContrarian(timeframe,period){const map=timeframeState.get(timeframe);if(!map)return null;const rows=symbols.map(symbol=>({symbol,state:map.get(symbol)||empty()}));if(rows.some(row=>row.state.lastBucket!==period||row.state.imbalanceUsd===0))return null;const positives=rows.filter(row=>row.state.imbalanceUsd>0),negatives=rows.filter(row=>row.state.imbalanceUsd<0);if(positives.length===6&&negatives.length===1)return{candidate:negatives[0],majoritySign:1};if(negatives.length===6&&positives.length===1)return{candidate:positives[0],majoritySign:-1};return null;}
async function processHistorical(timeframe){for(const symbol of symbols){const result=await fetchHistoricalEvents(symbol,timeframe),grouped=new Map();for(const event of result.events){const bucket=grouped.get(event.period)||{longUsd:0,shortUsd:0};bucket.longUsd+=event.longUsd;bucket.shortUsd+=event.shortUsd;grouped.set(event.period,bucket);}for(const[period,bucket]of[...grouped.entries()].sort((a,b)=>a[0]-b[0]))applyCompletedBucket(timeframe,symbol,period,bucket.longUsd,bucket.shortUsd);}}
async function processLive(timeframe,boundary){if(!ALERT_FRAMEWORKS.includes(timeframe))return;const period=bucketStart(boundary-1,timeframe);await Promise.all(symbols.map(async symbol=>{const events=await fetchSymbolFeed(symbol);let longUsd=0,shortUsd=0,longEvents=0,shortEvents=0;for(const event of events||[]){const ts=normalizeTs(event);if(!Number.isFinite(ts)||bucketStart(ts,timeframe)!==period)continue;const direction=side(event),value=notional(event);if(direction>0){longUsd+=value;longEvents++;}else if(direction<0){shortUsd+=value;shortEvents++;}}const state=applyCompletedBucket(timeframe,symbol,period,longUsd,shortUsd,longEvents,shortEvents);if(state)console.log(JSON.stringify({timeframe,symbol,period,longUsd,shortUsd,imbalanceUsd:state.imbalanceUsd}));}));const result=detectContrarian(timeframe,period);if(result)await sendContrarianAlert(timeframe,period,result.candidate,result.majoritySign);else console.log(`NO 6-VS-1 CONTRARIAN ${timeframe} period=${period}`);if(timeframe==='5m')return;const rows=symbols.map(symbol=>({symbol,state:timeframeState.get(timeframe).get(symbol)||empty()})).filter(row=>row.state.lastBucket===period&&row.state.imbalanceUsd!==0);if(!rows.length)return;rows.sort((a,b)=>Math.abs(b.state.imbalanceUsd)-Math.abs(a.state.imbalanceUsd));await sendLargestAlert(timeframe,period,rows[0]);}
async function main(){await loadState();console.log('Liquidation monitor started; 5m=6-vs-1 contrarian; 15m=inverted direction + largest + contrarian; 1h/4h=largest + contrarian');await processHistorical('15m');await processHistorical('1h');await processHistorical('4h');await saveState();while(true){const now=Date.now(),boundary=nextBoundary(now),wait=Math.max(1000,boundary-now+BOUNDARY_GRACE_MS);console.log(`Waiting for next timeframe boundary in ${Math.round(wait/1000)}s`);await sleep(wait);const current=Date.now();for(const timeframe of FRAMEWORKS){const due=bucketStart(current,timeframe);if(Math.abs(current-due)<=BOUNDARY_GRACE_MS*2){console.log(`TIMEFRAME BOUNDARY REACHED; due=${timeframe}`);await processLive(timeframe,due);}}await saveState();}}
main().catch(error=>{console.error(error);process.exitCode=1;});
