const https=require('https');
const {fetchSymbolFeed,normalizeTs}=require('./liquidation-monitor');
const {TIMEFRAMES,findNextMarket}=require('./polymarket');
const {sendTelegramMessage}=require('./telegram');
const symbols=['BTC','ETH','SOL','XRP','DOGE','BNB','HYPE'];
const FRAMEWORKS=['5m','15m','1h','4h'];
const disabledSymbolsByTimeframe={'5m':[],'15m':[],'1h':[],'4h':[]};
const BOUNDARY_GRACE_MS=1500,REQUEST_TIMEOUT_MS=15000,STATE_PATH='.monitor-state.json';
const STATE_API_URL=`https://api.github.com/repos/${process.env.GITHUB_REPOSITORY||'laudinvil/Polymarket-Perps-Monitor'}/contents/${STATE_PATH}?ref=monitor-status`;
const HISTORICAL_URL='https://marginpad.io/api/v1/liquidations/recent';
const sentAlerts=new Set(),timeframeState=new Map(),contrarianState=new Map();let stateSha=null;
function empty(){return{imbalanceUsd:0,longUsd:0,shortUsd:0,longEvents:0,shortEvents:0,events:0,establishedSign:0,lastBucket:null,buckets:{}}}
for(const t of FRAMEWORKS){timeframeState.set(t,new Map());contrarianState.set(t,{symbol:null,sign:0})}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function bucketStart(ts,t){return Math.floor(ts/TIMEFRAMES[t])*TIMEFRAMES[t]}
function nextBoundary(ts){let n=Infinity;for(const t of FRAMEWORKS)n=Math.min(n,bucketStart(ts,t)+TIMEFRAMES[t]);return n}
function formatUsd(v){const s=v>0?'+':v<0?'-':'';return`${s}$${Math.round(Math.abs(v)).toLocaleString('en-US')}`}
function side(e){const s=String(e?.side||e?.direction||'').toLowerCase();return s.includes('long')?1:s.includes('short')?-1:0}
function notional(e){const n=Number(e?.notional??e?.usd??e?.value??e?.amount);return Number.isFinite(n)?Math.abs(n):0}
function githubRequest(method='GET',body){return new Promise((resolve,reject)=>{const u=new URL(STATE_API_URL),req=https.request({hostname:u.hostname,path:u.pathname+u.search,method,timeout:REQUEST_TIMEOUT_MS,headers:{'User-Agent':'Polymarket-Perps-Monitor','Accept':'application/vnd.github+json','Authorization':`Bearer ${process.env.GITHUB_TOKEN||''}`,'X-GitHub-Api-Version':'2022-11-28'}},res=>{let d='';res.setEncoding('utf8');res.on('data',c=>d+=c);res.on('end',()=>{let p=null;try{p=d?JSON.parse(d):null}catch{}if(res.statusCode>=200&&res.statusCode<300)return resolve(p);const e=new Error(`GitHub state request failed: ${res.statusCode} ${d}`);e.statusCode=res.statusCode;reject(e)})});req.on('timeout',()=>req.destroy(new Error('GitHub state request timed out')));req.on('error',reject);if(body!==undefined)req.write(JSON.stringify(body));req.end()})}
function buildStatePayload(){const liquidationTimeframes={};for(const t of FRAMEWORKS){liquidationTimeframes[t]={};for(const s of symbols)liquidationTimeframes[t][s]=timeframeState.get(t).get(s)||empty()}return{version:7,updatedAt:new Date().toISOString(),sentAlerts:[...sentAlerts],liquidationTimeframes,contrarianTimeframes:Object.fromEntries(FRAMEWORKS.map(t=>[t,contrarianState.get(t)||{symbol:null,sign:0}]))}}
function migrateAlertKey(k){if(typeof k!=='string')return null;const m=k.match(/^(5m|15m|1h|4h|1d):([A-Z]+):(\d+):(-?1)$/);if(m)return k;const l=k.match(/^(5m|15m|1h|4h|1d):([A-Z]+):(\d+):(-?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?)$/i);if(!l)return null;const v=Number(l[4]);return Number.isFinite(v)&&v!==0?`${l[1]}:${l[2]}:${l[3]}:${v>0?1:-1}`:null}
function mergeAlerts(st){for(const k of[...(st?.sentAlerts||[]),...(st?.alerts||[])]){const m=migrateAlertKey(k);if(m)sentAlerts.add(m)}}
function normalizeSavedState(saved){const st={...empty(),...saved,buckets:saved?.buckets&&typeof saved.buckets==='object'?saved.buckets:{}};const periods=Object.keys(st.buckets).map(Number).filter(Number.isFinite).sort((a,b)=>a-b);const lp=st.lastBucket!==null&&Number.isFinite(Number(st.lastBucket))?Number(st.lastBucket):periods.at(-1);const b=lp!==undefined?st.buckets[String(lp)]:null;if(b){st.lastBucket=lp;st.longUsd=Math.max(0,Number(b.longUsd)||0);st.shortUsd=Math.max(0,Number(b.shortUsd)||0);st.longEvents=Math.max(0,Number(b.longEvents)||0);st.shortEvents=Math.max(0,Number(b.shortEvents)||0)}else{st.longUsd=Math.max(0,Number(st.longUsd)||0);st.shortUsd=Math.max(0,Number(st.shortUsd)||0);st.longEvents=Math.max(0,Number(st.longEvents)||0);st.shortEvents=Math.max(0,Number(st.shortEvents)||0)}st.events=st.longEvents+st.shortEvents;st.imbalanceUsd=st.shortUsd-st.longUsd;st.establishedSign=st.imbalanceUsd>0?1:st.imbalanceUsd<0?-1:0;return st}
async function loadState(){if(!process.env.GITHUB_TOKEN)return;try{const r=await githubRequest();stateSha=r?.sha||null;if(!r?.content)return;const st=JSON.parse(Buffer.from(r.content.replace(/\s/g,''),'base64').toString('utf8'));mergeAlerts(st);for(const t of FRAMEWORKS){const m=timeframeState.get(t);for(const s of symbols){const saved=st.liquidationTimeframes?.[t]?.[s];if(saved)m.set(s,normalizeSavedState(saved))}const c=st.contrarianTimeframes?.[t];if(c)contrarianState.set(t,{symbol:c.symbol||null,sign:Number(c.sign)||0})}console.log(`STATE LOADED ${st.updatedAt||'unknown'}; independent timeframe windows restored`)}catch(e){if(e.statusCode===404)console.log('STATE LOAD: no persisted state found; starting clean');else console.warn(`STATE LOAD FAILED: ${e.message}`)}}
async function saveState(){if(!process.env.GITHUB_TOKEN)return false;for(let a=1;a<=5;a++)try{let r=null;try{r=await githubRequest()}catch(e){if(e.statusCode!==404)throw e}stateSha=r?.sha||null;if(r?.content)try{mergeAlerts(JSON.parse(Buffer.from(r.content.replace(/\s/g,''),'base64').toString('utf8')))}catch{}const p=buildStatePayload(),body={message:'Persist liquidation monitor state',content:Buffer.from(JSON.stringify(p,null,2)).toString('base64'),branch:'monitor-status',...(stateSha?{sha:stateSha}:{})};const out=await githubRequest('PUT',body);stateSha=out?.content?.sha||stateSha;console.log(`STATE SAVED ${p.updatedAt}`);return true}catch(e){if(e.statusCode!==409||a===5){console.warn(`STATE SAVE FAILED: ${e.message}`);return false}await sleep(250*a)}return false}
async function reserveAlertKey(k){if(sentAlerts.has(k)){console.log(`ALERT DUPLICATE SUPPRESSED ${k}`);return false}if(!process.env.GITHUB_TOKEN)return true;try{const r=await githubRequest();if(r?.content){const st=JSON.parse(Buffer.from(r.content.replace(/\s/g,''),'base64').toString('utf8'));const keys=new Set([...(st.sentAlerts||[]),...(st.alerts||[])].map(migrateAlertKey).filter(Boolean));if(keys.has(k)){sentAlerts.add(k);console.log(`ALERT DUPLICATE SUPPRESSED ${k}`);return false}}return true}catch(e){console.warn(`ALERT DEDUP CHECK FAILED ${k}: ${e.message}`);return false}}
async function markAlertSent(k){sentAlerts.add(k);await saveState();console.log(`ALERT MARKED SENT ${k}`)}
function extractHistoricalBuckets(json){const roots=[json?.data,json],cand=['buckets','histogram','rows','series','bars','points','items','data'],seen=new Set(),q=roots.map(value=>({value,depth:0}));while(q.length){const{value,depth}=q.shift();if(!value||depth>3||typeof value!=='object'||seen.has(value))continue;seen.add(value);if(Array.isArray(value)){if(value.some(r=>r&&typeof r==='object'&&!Array.isArray(r)))return value;continue}for(const k of cand)if(Array.isArray(value[k])&&value[k].length)return value[k];for(const c of Object.values(value))if(c&&typeof c==='object')q.push({value:c,depth:depth+1})}return[]}
function numericValue(v){if(v===null||v===undefined||v==='')return 0;if(typeof v==='number')return Number.isFinite(v)?v:0;if(typeof v==='object'){for(const k of['usd','value','notional','amount','total','volume','vol']){const n=numericValue(v[k]);if(n)return n}return 0}const n=Number(String(v).replace(/[$,\s]/g,''));return Number.isFinite(n)?n:0}
function bucketValue(row,names,direction){for(const n of names){const v=numericValue(row?.[n]);if(v!==0)return Math.abs(v)}if(row&&typeof row==='object')for(const[k,raw]of Object.entries(row)){const l=k.toLowerCase();if(!l.includes(direction))continue;if(!/(usd|notional|volume|value|amount|liquid)/i.test(l)&&l!==direction)continue;const v=numericValue(raw);if(v!==0)return Math.abs(v)}return 0}
function normalizeHistoricalTimestamp(v){if(v===null||v===undefined||v==='')return null;if(Array.isArray(v))return normalizeHistoricalTimestamp(v[0]);if(typeof v==='object'){for(const k of['$date','date','timestamp','ts','time','start','startTime','epoch'])if(Object.prototype.hasOwnProperty.call(v,k)){const t=normalizeHistoricalTimestamp(v[k]);if(t)return t}return null}if(typeof v==='string'){const n=Number(v.trim());if(Number.isFinite(n)&&n>0)return normalizeHistoricalTimestamp(n);const p=Date.parse(v.trim());return Number.isFinite(p)&&p>0?p:null}const n=Number(v);if(!Number.isFinite(n)||n<=0)return null;if(n<1e11)return n*1000;if(n<1e14)return n;if(n<1e17)return n/1000;return n/1e6}
function historicalRowTs(row){if(Array.isArray(row))return normalizeHistoricalTimestamp(row[0]);for(const k of['ts','timestamp','time','t','bucket','start','startTime','start_ts','startTimeMs','bucketStart','bucket_start','epoch','date']){const t=normalizeHistoricalTimestamp(row?.[k]);if(t)return t}if(row&&typeof row==='object')for(const[k,v]of Object.entries(row))if(/(time|timestamp|bucket|start|epoch|date|^ts$)/i.test(k)){const t=normalizeHistoricalTimestamp(v);if(t)return t}return null}
async function fetchHistoricalEvents(symbol,timeframe){const minutes=({'15m':15,'1h':60,'4h':240})[timeframe];if(!minutes)return{events:[],buckets:new Set()};const url=`${HISTORICAL_URL}?symbol=${encodeURIComponent(symbol)}&minutes=${Math.max(minutes*2,60)}`;try{const r=await fetch(url,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`MarginPad historical request failed: ${r.status}`);const rows=extractHistoricalBuckets(await r.json()),events=[],buckets=new Set();for(const row of rows){const ts=historicalRowTs(row);if(!ts)continue;const period=bucketStart(ts,timeframe);buckets.add(period);const longUsd=bucketValue(row,['long_liquidations','longLiquidations','long_usd','longUsd','long_volume','longVolume','longNotional','long_notional','long','buy'],'long'),shortUsd=bucketValue(row,['short_liquidations','shortLiquidations','short_usd','shortUsd','short_volume','shortVolume','shortNotional','short_notional','short','sell'],'short');if(longUsd>0||shortUsd>0)events.push({symbol,ts,period,longUsd,shortUsd})}console.log(`HISTORICAL ${timeframe} ${symbol}: rows=${rows.length} buckets=${buckets.size} events=${events.length}`);return{events,buckets}}catch(e){console.warn(`HISTORICAL ${timeframe} ${symbol} FAILED: ${e.message}`);return{events:[],buckets:new Set()}}}
function applyCompletedBucket(timeframe,symbol,period,longUsd,shortUsd,longEvents=0,shortEvents=0){const map=timeframeState.get(timeframe);if(!map)return null;let state=map.get(symbol)||empty();state=normalizeSavedState(state);if(state.lastBucket!==null&&period<=state.lastBucket)return null;longUsd=Math.max(0,Number(longUsd)||0);shortUsd=Math.max(0,Number(shortUsd)||0);state.longUsd=longUsd;state.shortUsd=shortUsd;state.longEvents=Math.max(0,Number(longEvents)||0);state.shortEvents=Math.max(0,Number(shortEvents)||0);state.events=state.longEvents+state.shortEvents;state.imbalanceUsd=state.shortUsd-state.longUsd;state.establishedSign=state.imbalanceUsd>0?1:state.imbalanceUsd<0?-1:0;state.lastBucket=period;state.buckets[String(period)]={longUsd,shortUsd,longEvents:state.longEvents,shortEvents:state.shortEvents};map.set(symbol,state);return state}
function crossingFor(timeframe,symbol,before,after,period){if(before===after)return null;if(before===0&&after===0)return null;if(before!==0&&after!==0&&Math.sign(before)===Math.sign(after))return null;if(after===0)return null;return{timeframe,symbol,before,after,period}}
async function sendCrossingAlert(crossing,state,longUsd,shortUsd,longEvents,shortEvents){const alertKey=`${crossing.timeframe}:${crossing.symbol}:${crossing.period}:${crossing.after>0?1:-1}`;if(!(await reserveAlertKey(alertKey)))return;let market=null;try{market=await findNextMarket(crossing.symbol,Date.now(),crossing.timeframe)}catch(e){console.warn(`POLYMARKET LOOKUP FAILED ${crossing.timeframe} ${crossing.symbol}: ${e.message}`)}const signal=crossing.timeframe==='5m'?'BUY UP':crossing.after>0?'BUY UP':'BUY DOWN',color='🟢',link=market?.url?`\n➡️ NEXT Polymarket ${crossing.timeframe}\n${market.url}`:'';const msg=`${color} ${crossing.symbol} · ${crossing.timeframe} · ${signal}\n\nPrevious imbalance: ${formatUsd(crossing.before)}\nNew imbalance: ${formatUsd(crossing.after)}\n${formatUsd(longUsd)} LONG · ${formatUsd(-shortUsd)} SHORT${link}`;try{await sendTelegramMessage(msg);await markAlertSent(alertKey);console.log(`ZERO CROSSING ALERT SENT ${crossing.timeframe} ${crossing.symbol} ${signal}`)}catch(e){console.warn(`ZERO CROSSING ALERT SEND FAILED ${crossing.timeframe} ${crossing.symbol}: ${e.message}`)}}
function detectContrarian(timeframe,period){const map=timeframeState.get(timeframe);if(!map)return null;const rows=symbols.map(symbol=>({symbol,state:map.get(symbol)||empty()})),signs=rows.map(r=>r.state.imbalanceUsd>0?1:r.state.imbalanceUsd<0?-1:0);if(signs.includes(0))return null;const pos=rows.filter((_,i)=>signs[i]>0),neg=rows.filter((_,i)=>signs[i]<0);let c=null;if(pos.length===1&&neg.length===6)c=pos[0];else if(neg.length===1&&pos.length===6)c=neg[0];if(!c)return null;const sign=c.state.imbalanceUsd>0?1:-1,prev=contrarianState.get(timeframe)||{symbol:null,sign:0};if(prev.symbol===c.symbol)return null;contrarianState.set(timeframe,{symbol:c.symbol,sign});return{symbol:c.symbol,sign,state:c.state,period}}
async function processHistorical(timeframe){for(const symbol of symbols){const map=timeframeState.get(timeframe);if(!map)continue;const result=await fetchHistoricalEvents(symbol,timeframe),grouped=new Map();for(const e of result.events){const b=grouped.get(e.period)||{longUsd:0,shortUsd:0};b.longUsd+=e.longUsd;b.shortUsd+=e.shortUsd;grouped.set(e.period,b)}for(const[period,b]of[...grouped.entries()].sort((a,b)=>a[0]-b[0])){const st=map.get(symbol)||empty();if(st.lastBucket!==null&&period<=st.lastBucket)continue;applyCompletedBucket(timeframe,symbol,period,b.longUsd,b.shortUsd)}}}
async function processLive(timeframe,boundary){const period=bucketStart(boundary-1,timeframe),disabled=new Set(disabledSymbolsByTimeframe[timeframe]||[]),active=symbols.filter(s=>!disabled.has(s));await Promise.all(active.map(async symbol=>{const events=await fetchSymbolFeed(symbol);const previous=timeframeState.get(timeframe).get(symbol)||empty();const before=previous.imbalanceUsd;let longUsd=0,shortUsd=0,longEvents=0,shortEvents=0;for(const e of events||[]){const ts=normalizeTs(e);if(!Number.isFinite(ts)||bucketStart(ts,timeframe)!==period)continue;const s=side(e),v=notional(e);if(s>0){longUsd+=v;longEvents++}else if(s<0){shortUsd+=v;shortEvents++}}const next=applyCompletedBucket(timeframe,symbol,period,longUsd,shortUsd,longEvents,shortEvents);if(!next)return;console.log(JSON.stringify({timeframe,symbol,period,longUsd,shortUsd,imbalanceUsd:next.imbalanceUsd,establishedSign:next.establishedSign,lastBucket:next.lastBucket}));const crossing=crossingFor(timeframe,symbol,before,next.imbalanceUsd,period);if(crossing)await sendCrossingAlert(crossing,next,longUsd,shortUsd,longEvents,shortEvents)}));const c=detectContrarian(timeframe,period);if(c)await sendContrarianAlert(timeframe,c.symbol,c.sign,c.period,c.state)}
async function main(){await loadState();console.log('Liquidation monitor started; zero-crossing + 6-vs-1 contrarian; independent windows: 5m,15m,1h,4h');await processHistorical('15m');await processHistorical('1h');await processHistorical('4h');await saveState();while(true){const now=Date.now(),boundary=nextBoundary(now),wait=Math.max(1000,boundary-now+BOUNDARY_GRACE_MS);console.log(`Waiting for next timeframe boundary in ${Math.round(wait/1000)}s`);await sleep(wait);const current=Date.now();for(const timeframe of FRAMEWORKS){const due=bucketStart(current,timeframe);if(Math.abs(current-due)<=BOUNDARY_GRACE_MS*2){console.log(`TIMEFRAME BOUNDARY REACHED; due=${timeframe}`);await processLive(timeframe,due)}}await saveState()}}
main().catch(e=>{console.error(e);process.exitCode=1})