import fs from 'node:fs';
const KEY=process.env.PINAX_API_KEY||process.env.PINAX_API_TOKEN;
const TG_TOKEN=process.env.TELEGRAM_BOT_TOKEN, TG_CHAT=process.env.TELEGRAM_CHAT_ID;
const ASSETS=['BTC','ETH','XRP','SOL','DOGE','HYPE','BNB'];
const PINAX_URL='https://api.pinax.network/v1/hyperliquid/markets/liquidations';
const STATE='src/spike-alerted-windows.json';
const RUN_ONCE=process.env.RUN_ONCE==='true';
const LIMIT=100, MAX_PAGES_PER_COIN=5, PAGE_DELAY_MS=150, COIN_DELAY_MS=150;
const MIN_USERS=2;
const WINDOW=5*60*1000;
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function num(...v){for(const x of v){const n=Number(x);if(Number.isFinite(n))return n;}return 0;}
function ts(x){const v=x?.timestamp??x?.time??x?.created_at??x?.createdAt??x?.block_time??x?.blockTime;if(v==null)return 0;if(typeof v==='number')return v<1e12?v*1000:v;const s=String(v);const iso=s.includes('T')?s:s.replace(' ','T')+'Z';const n=Date.parse(iso);return Number.isFinite(n)?n:Date.parse(s);}
function user(x){return String(x?.liquidated_user??x?.liquidatedUser??x?.user??x?.address??x?.wallet??x?.account??'').toLowerCase();}
function usd(x){return `${Number(x).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})} USDT`;}
async function page(coin,start,end,p){const u=new globalThis.URL(PINAX_URL);u.searchParams.set('coin',coin);u.searchParams.set('dex','perps');u.searchParams.set('sort_by','time');u.searchParams.set('start_time',new Date(start).toISOString());u.searchParams.set('end_time',new Date(end).toISOString());u.searchParams.set('limit',String(LIMIT));u.searchParams.set('page',String(p));if(p>1)await sleep(PAGE_DELAY_MS);const t=Date.now();const r=await fetch(u,{headers:{Authorization:`Bearer ${KEY}`,Accept:'application/json'}});const raw=await r.text();if(!r.ok)throw Error(`HTTP ${r.status}: ${raw.slice(0,300)}`);let b;try{b=JSON.parse(raw);}catch{throw Error('Pinax returned non-JSON response');}const rows=Array.isArray(b?.data)?b.data:[];console.log(`[SPIKE][PINAX-LIQ] ${coin} page=${p}/${MAX_PAGES_PER_COIN} rows=${rows.length} latency=${Date.now()-t}ms`);return rows;}
async function collect(coin,start,end){const out=[];let pages=0;let oldest=0;for(let p=1;p<=MAX_PAGES_PER_COIN;p++){const rows=await page(coin,start,end,p);pages=p;out.push(...rows);const times=rows.map(ts).filter(Boolean);if(times.length)oldest=Math.min(...times);if(rows.length<LIMIT)break;if(oldest&&oldest<=start)break;}const filtered=out.filter(x=>{const t=ts(x);return t>=start&&t<end;});if(pages===MAX_PAGES_PER_COIN&&oldest>start)console.log(`[SPIKE][WARNING] ${coin} reached max pages before covering full window; oldest=${new Date(oldest).toISOString()}`);console.log(`[SPIKE][FILTER] ${coin} pages=${pages} fetched=${out.length} liquidations=${filtered.length}`);return filtered;}
function analyze(rows){const users=new Set();let volume=0,long=0,short=0;for(const x of rows){const u=user(x);if(u)users.add(u);const d=String(x?.direction??x?.liquidation_kind??'').toUpperCase();if(d.includes('LONG'))long++;else if(d.includes('SHORT'))short++;volume+=Math.abs(num(x?.notional,x?.total_notional,x?.positionValue,x?.position_value,x?.sizeUsd,x?.usdValue,x?.value));}return{users:users.size,events:rows.length,volume,long,short};}
function market(coin,start){return `https://polymarket.com/event/${coin.toLowerCase()}-updown-5m-${Math.floor((start+WINDOW)/1000)}`;}
function loadState(){try{return JSON.parse(fs.readFileSync(STATE,'utf8'));}catch{return{};}}
function saveState(s){fs.writeFileSync(STATE,JSON.stringify(s,null,2)+'\n');}
async function telegram(text){if(!TG_TOKEN||!TG_CHAT)return;const r=await fetch(`https://api.telegram.org/bot${TG_TOKEN}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:TG_CHAT,text,disable_web_page_preview:false})});if(!r.ok)throw Error(`Telegram HTTP ${r.status}: ${(await r.text()).slice(0,200)}`);}
async function runWindow(start){const end=start+WINDOW;const state=loadState();const key=`5:${start}`;if(state[key]){console.log(`[SPIKE][SKIP] already checked ${key}`);return;}console.log(`[SPIKE][WINDOW] 5M ${new Date(start).toISOString()}..${new Date(end).toISOString()}`);const results=[];for(const coin of ASSETS){try{const rows=await collect(coin,start,end);results.push({coin,...analyze(rows)});}catch(e){console.log(`[SPIKE][ERROR] ${coin} ${e.message}`);}await sleep(COIN_DELAY_MS);}const qualified=results.filter(x=>x.users>=MIN_USERS).sort((a,b)=>b.users-a.users||b.volume-a.volume);if(qualified.length){const x=qualified[0];console.log(`[SPIKE][5M] ${x.coin} users=${x.users} events=${x.events} volume=${usd(x.volume)} long=${x.long} short=${x.short}`);await telegram(`🔥 LIQUIDATION SPIKE\n\n${x.coin} — 5M\nLiquidated users: ${x.users}\nLiquidation events: ${x.events}\nVolume: ${usd(x.volume)}\nLong: ${x.long} | Short: ${x.short}\n\n▶️ NEXT POLYMARKET 5M\n${market(x.coin,start)}`);}else console.log(`[SPIKE][5M] no coin reached ${MIN_USERS} unique users`);state[key]=true;saveState(state);}
async function main(){console.log('=== LIQUIDATION SPIKE MONITOR ===');console.log('SOURCE: PINAX HYPERLIQUID MARKET LIQUIDATIONS');console.log('PERIOD: 5M ONLY');console.log(`PAGINATION: max=${MAX_PAGES_PER_COIN} pages/coin, limit=${LIMIT}`);if(!KEY)throw Error('PINAX_API_KEY/PINAX_API_TOKEN is not configured');let cursor=Math.floor(Date.now()/WINDOW)*WINDOW-WINDOW;while(true){const start=cursor;await runWindow(start);if(RUN_ONCE){console.log('[RUN_ONCE] SPIKE window complete; exiting.');return;}cursor=start+WINDOW;const wait=Math.max(1000,cursor+WINDOW-Date.now());console.log(`[SPIKE][SLEEP] next closed 5M window check in ${Math.round(wait/1000)}s`);await sleep(wait);}}
main().catch(e=>{console.error(`[FATAL] ${e.message}`);process.exit(1);});
